### get owner
GET http://localhost:8082/owners/2



### add owner
POST http://localhost:8082/owners/add
Content-Type: application/json

{
"password": "hunter2",
  "email": "e@mail.com",
  "name": "Maciek",
  "surname": "WisłaKraków"
}

### add house
POST http://localhost:8082/houses/add
Content-Type: application/json

{
  "ownerId": 1,
  "address": "Wlokniarzy",
  "name": "Domek 1",
  "daytimeTariff": 0.5803,
  "nightTariff": 0.3672
}
### remove house
DELETE http://localhost:8082/houses/remove/1




### add room
POST http://localhost:8082/rooms/add
Content-Type: application/json

{
  "houseId": 1,
  "name": "Pokój 1"
}
### remove room
DELETE http://localhost:8082/rooms/remove/1

### add device
POST http://localhost:8082/devices/add
Content-Type: application/json

{
  "roomId": 1,
  "name": "Lampka",
  "powerConsumption": 200
}
### remove device
DELETE http://localhost:8082/devices/remove/1


### add generator
POST http://localhost:8082/generators/add
Content-Type: application/json

{
  "houseId": 1,
  "name": "Generator 1",
  "effectiveness": 0.5,
  "batteryCapacity": 100,
  "wattage": 300
}
### remove generator
DELETE http://localhost:8082/generators/remove/1

### add interval
POST http://localhost:8082/intervals/add
Content-Type: application/json

{
  "deviceId": 1,
  "timeStart": "09:00",
  "timeEnd": "11:00"
}
### remove interval
DELETE http://localhost:8082/intervals/remove/1






### get daily power graph
POST http://localhost:8082/dailyPowerGraph
Content-Type: application/json

{
  "houseId": 2
}


### get daily costs graph
POST http://localhost:8082/dailyCostsGraph
Content-Type: application/json

{
  "houseId": 1
}

### get daily cost
POST http://localhost:8082/dailyCost
Content-Type: application/json

{
  "houseId": 1
}

### get daily energy produced
POST http://localhost:8082/dailyEnergyProduced
Content-Type: application/json

{
  "houseId": 1
}