### get owner
GET http://localhost:8082/owners/1



### add owner
POST http://localhost:8082/owners/add
Content-Type: application/json

{
"password": "hunter2",
  "email": "e@mail.com",
  "name": "Maciek",
  "surname": "WisłaKraków"
}

### add house
POST http://localhost:8082/houses/add
Content-Type: application/json

{
  "ownerId": 1,
  "address": "Wlokniarzy",
  "name": "Domek 1",
  "daytimeTariff": 0.5803,
  "nightTariff": 0.3672
}




### add room
POST http://localhost:8082/rooms/add
Content-Type: application/json

{
  "houseId": 1,
  "name": "Pokój 1"
}

### add device
POST http://localhost:8082/devices/add
Content-Type: application/json

{
  "roomId": 1,
  "name": "Lampka",
  "powerConsumption": 200
}

### add device
POST http://localhost:8082/devices/add
Content-Type: application/json

{
  "roomId": 1,
  "name": "Lampka2",
  "powerConsumption": 400
}


### add generator
POST http://localhost:8082/generators/add
Content-Type: application/json

{
  "houseId": 1,
  "name": "Generator 1",
  "effectiveness": 0.5,
  "batteryCapacity": 100,
  "wattage": 300
}

### add interval1
POST http://localhost:8082/intervals/add
Content-Type: application/json

{
  "deviceId": 1,
  "timeStart": "00:00",
  "timeEnd": "08:00"
}

### add interval2
POST http://localhost:8082/intervals/add
Content-Type: application/json

{
  "deviceId": 2,
  "timeStart": "07:00",
  "timeEnd": "23:30"
}

### get daily power graph
GET http://localhost:8082/dailyPowerGraph
Content-Type: application/json

{
  "houseId": 1
}

### get daily costs graph
GET http://localhost:8082/dailyCostsGraph
Content-Type: application/json

{
  "houseId": 1
}
